### ISSUE TITLE
Apparently unnecessary warning message in logbin

### ISSUE THREAD

**Issue by SebVen** [mdonoghoe/logbin#2]
It seems that the `logbin()` function reports the following warning message irrespective of any attempt to remediate the issue: 

`Warning message:`
`In model.response(mf, "numeric") :`
`  using type = "numeric" with a factor response will be ignored`

For other models (e.g. `lm()`) this type of warning is given when an incorrect variable type is used as a response variable. In this case, `logbin()` warns that the variable type must be `numeric`. However, the response variable required for log-binomial regression and hence the `logbin()` function is of type `factor`.

To reproduce the issue:

`df <- data.frame(x = as.factor(c(2,2,1,2,1,2,1)), y = as.factor(c(1,2,2,2,1,2,1)))`
`logbin(y ~ x, data = df, trace = 1)`

Logbin package version: 2.0.3

**Comment by mdonoghoe** [comment]
Thanks, this is fixed now
